/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.proxy.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2022-06-28")
public enum CompactionReason implements org.apache.thrift.TEnum {
  USER(0),
  SYSTEM(1),
  CHOP(2),
  IDLE(3),
  CLOSE(4);

  private final int value;

  private CompactionReason(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CompactionReason findByValue(int value) { 
    switch (value) {
      case 0:
        return USER;
      case 1:
        return SYSTEM;
      case 2:
        return CHOP;
      case 3:
        return IDLE;
      case 4:
        return CLOSE;
      default:
        return null;
    }
  }
}
