/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.proxy.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2022-06-28")
public enum CompactionType implements org.apache.thrift.TEnum {
  MINOR(0),
  MERGE(1),
  MAJOR(2),
  FULL(3);

  private final int value;

  private CompactionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CompactionType findByValue(int value) { 
    switch (value) {
      case 0:
        return MINOR;
      case 1:
        return MERGE;
      case 2:
        return MAJOR;
      case 3:
        return FULL;
      default:
        return null;
    }
  }
}
