/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.proxy.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2022-06-28")
public enum ConditionalStatus implements org.apache.thrift.TEnum {
  ACCEPTED(0),
  REJECTED(1),
  VIOLATED(2),
  UNKNOWN(3),
  INVISIBLE_VISIBILITY(4);

  private final int value;

  private ConditionalStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ConditionalStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return ACCEPTED;
      case 1:
        return REJECTED;
      case 2:
        return VIOLATED;
      case 3:
        return UNKNOWN;
      case 4:
        return INVISIBLE_VISIBILITY;
      default:
        return null;
    }
  }
}
