/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.proxy.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2022-06-28")
public enum NamespacePermission implements org.apache.thrift.TEnum {
  READ(0),
  WRITE(1),
  ALTER_NAMESPACE(2),
  GRANT(3),
  ALTER_TABLE(4),
  CREATE_TABLE(5),
  DROP_TABLE(6),
  BULK_IMPORT(7),
  DROP_NAMESPACE(8);

  private final int value;

  private NamespacePermission(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static NamespacePermission findByValue(int value) { 
    switch (value) {
      case 0:
        return READ;
      case 1:
        return WRITE;
      case 2:
        return ALTER_NAMESPACE;
      case 3:
        return GRANT;
      case 4:
        return ALTER_TABLE;
      case 5:
        return CREATE_TABLE;
      case 6:
        return DROP_TABLE;
      case 7:
        return BULK_IMPORT;
      case 8:
        return DROP_NAMESPACE;
      default:
        return null;
    }
  }
}
